services:
  customer_service_test:
    build:
      context: .
      dockerfile: ./customer_service/Dockerfile
    volumes:
      - ./customer_service:/app/customer_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r customer_service/requirements-test.txt &&
               pytest --cov=customer_service customer_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  account_service_test:
    build:
      context: .
      dockerfile: ./account_service/Dockerfile
    volumes:
      - ./account_service:/app/account_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r account_service/requirements-test.txt &&
               pytest --cov=account_service account_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
      - test_network

  auth_service_test:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    volumes:
      - ./auth_service:/app/auth_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r auth_service/requirements-test.txt > /dev/null &&
               pytest --cov=auth_service auth_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
      - test_network

  security_service_test:
    build:
      context: .
      dockerfile: ./security_service/Dockerfile
    volumes:
      - ./security_service:/app/security_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r security_service/requirements-test.txt > /dev/null &&
               pytest --cov=security_service security_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  transaction_service_test:
    build:
      context: .
      dockerfile: ./transaction_service/Dockerfile
    volumes:
      - ./transaction_service:/app/transaction_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r transaction_service/requirements-test.txt > /dev/null &&
               pytest --cov=transaction_service transaction_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  notification_service_test:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
    volumes:
      - ./notification_service:/app/notification_service
    command: >
      bash -c "pip install --no-cache-dir -r notification_service/requirements-test.txt > /dev/null &&
               pytest --cov=notification_service notification_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
      - SMTP_HOST=smtp.example.com
      - SMTP_USER=test@example.com
    networks:
      - test_network

  metal_service_test:
    build:
      context: .
      dockerfile: ./metal_service/Dockerfile
    volumes:
      - ./metal_service:/app/metal_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r metal_service/requirements-test.txt > /dev/null &&
               pytest --cov=metal_service metal_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  currency_service_test:
    build:
      context: .
      dockerfile: ./currency_service/Dockerfile
    volumes:
      - ./currency_service:/app/currency_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r currency_service/requirements-test.txt > /dev/null &&
               pytest --cov=currency_service currency_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  log_service_test:
    build:
      context: .
      dockerfile: ./log_service/Dockerfile
    volumes:
      - ./log_service:/app/log_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r log_service/requirements-test.txt > /dev/null &&
               pytest --cov=log_service log_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
