services:
  customer_service_test:
    build:
      context: .
      dockerfile: ./customer_service/Dockerfile
    volumes:
      - ./customer_service:/app/customer_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r customer_service/requirements-test.txt &&
               pytest --cov=customer_service customer_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  account_service_test:
    build:
      context: .
      dockerfile: ./account_service/Dockerfile
    volumes:
      - ./account_service:/app/account_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r account_service/requirements-test.txt &&
               pytest --cov=account_service account_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
      - test_network

  auth_service_test:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    volumes:
      - ./auth_service:/app/auth_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r auth_service/requirements-test.txt > /dev/null &&
               pytest --cov=auth_service auth_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
      - test_network

  security_service_test:
    build:
      context: .
      dockerfile: ./security_service/Dockerfile
    volumes:
      - ./security_service:/app/security_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r security_service/requirements-test.txt > /dev/null &&
               pytest --cov=security_service security_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

  transaction_service_test:
    build:
      context: .
      dockerfile: ./transaction_service/Dockerfile
    volumes:
      - ./transaction_service:/app/transaction_service
      - ./shared:/app/shared
    command: >
      bash -c "pip install --no-cache-dir -r transaction_service/requirements-test.txt > /dev/null &&
               pytest --cov=transaction_service transaction_service/tests/unit/ -v"
    environment:
      - PYTHONPATH=/app
      - RUNNING_IN_DOCKER=true
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
