# Root Docker Compose (Monorepo)

include:
  - ./backend/docker-compose.yaml

services:
  # frontend:

networks:
  # Общие сети для связи между фронтендом и бэкендом
  frontend:
    driver: bridge
  backend:
    driver: bridge
  data:
    driver: bridge
