"""Add idempotency_key to transactions

Revision ID: f4d5e6a7b8c9
Revises: e373c764a397
Create Date: 2026-03-31 21:40:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4d5e6a7b8c9"
down_revision: str | None = "e373c764a397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column("transactions", sa.Column("idempotency_key", postgresql.UUID(as_uuid=True), nullable=True))
	op.create_index(op.f("ix_transactions_idempotency_key"), "transactions", ["idempotency_key"], unique=True)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
	op.drop_column("transactions", "idempotency_key")
	# ### end Alembic commands ###
