"""Add PII encryption and blind indexes"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import shared.models.types


# revision identifiers, used by Alembic.
revision: str = 'e373c764a397'
down_revision: Union[str, None] = 'add_passport_series_number_idx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_accounts_client_id'), table_name='bank_accounts')
    op.add_column('contacts', sa.Column('email_hash', sa.String(length=64), nullable=False))
    op.add_column('contacts', sa.Column('phone_hash', sa.String(length=64), nullable=False))
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.drop_constraint(op.f('contacts_email_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_phone_key'), 'contacts', type_='unique')
    op.create_index(op.f('ix_contacts_email_hash'), 'contacts', ['email_hash'], unique=True)
    op.create_index(op.f('ix_contacts_phone_hash'), 'contacts', ['phone_hash'], unique=True)
    op.alter_column('identifiers', 'inn',
               existing_type=sa.CHAR(length=12),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('identifiers', 'snils',
               existing_type=sa.CHAR(length=11),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.add_column('passport', sa.Column('passport_hash', sa.String(length=64), nullable=False))
    op.alter_column('passport', 'series',
               existing_type=sa.CHAR(length=4),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.alter_column('passport', 'number',
               existing_type=sa.CHAR(length=6),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.alter_column('passport', 'division_code',
               existing_type=sa.CHAR(length=7),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_passport_series_number'), 'passport', type_='unique')
    op.create_index(op.f('ix_passport_passport_hash'), 'passport', ['passport_hash'], unique=True)
    op.alter_column('personal_data', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.alter_column('personal_data', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=False)
    op.alter_column('personal_data', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               type_=shared.models.types.EncryptedString(),
               existing_nullable=True)
    op.alter_column('personal_data', 'gender',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_data', 'gender',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.alter_column('personal_data', 'middle_name',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('personal_data', 'first_name',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('personal_data', 'last_name',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_passport_passport_hash'), table_name='passport')
    op.create_unique_constraint(op.f('uq_passport_series_number'), 'passport', ['series', 'number'], postgresql_nulls_not_distinct=False)
    op.alter_column('passport', 'division_code',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.CHAR(length=7),
               existing_nullable=False)
    op.alter_column('passport', 'number',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.CHAR(length=6),
               existing_nullable=False)
    op.alter_column('passport', 'series',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.CHAR(length=4),
               existing_nullable=False)
    op.drop_column('passport', 'passport_hash')
    op.alter_column('identifiers', 'snils',
               existing_type=sa.String(length=11),
               type_=sa.CHAR(length=11),
               existing_nullable=False)
    op.alter_column('identifiers', 'inn',
               existing_type=sa.String(length=12),
               type_=sa.CHAR(length=12),
               existing_nullable=False)
    op.drop_index(op.f('ix_contacts_phone_hash'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email_hash'), table_name='contacts')
    op.create_unique_constraint(op.f('contacts_phone_key'), 'contacts', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_email_key'), 'contacts', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('contacts', 'phone',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('contacts', 'email',
               existing_type=shared.models.types.EncryptedString(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('contacts', 'phone_hash')
    op.drop_column('contacts', 'email_hash')
    op.create_index(op.f('ix_bank_accounts_client_id'), 'bank_accounts', ['client_id'], unique=False)
    # ### end Alembic commands ###
