// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Возвращает все счета текущего пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Список счетов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Создаёт банковский счёт указанного типа и валюты для текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Открыть новый счёт",
                "parameters": [
                    {
                        "description": "Тип и валюта счёта",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.OpenAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Возвращает данные конкретного счёта.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Детали счёта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/close": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Закрывает банковский счёт. Баланс должен быть 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Закрыть счёт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/deposit": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Вносит средства на указанный счёт.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Пополнить счёт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Сумма пополнения",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.AmountPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/freeze": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Замораживает счёт. Исходящие операции блокируются, входящие — разрешены.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Заморозить счёт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/transactions": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Возвращает историю операций по счёту с пагинацией и фильтрами.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "История операций",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Кол-во записей (по умолчанию 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип операции: deposit | withdrawal | transfer",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление: incoming | outgoing",
                        "name": "direction",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/transfer": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Переводит средства с указанного счёта на другой (свой или чужой).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Перевести между счетами",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта-отправителя",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные перевода",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/unfreeze": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Размораживает счёт. Доступно только если заморозка инициирована пользователем.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Разморозить счёт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/withdraw": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Списывает средства со счёта текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Снять со счёта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID счёта",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Сумма снятия",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.AmountPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login-pin": {
            "post": {
                "description": "Аутентификация по номеру телефона и PIN-коду. Возвращает сессионный токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход по PIN-коду",
                "parameters": [
                    {
                        "description": "Телефон и PIN",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.LoginPinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Завершает текущий сеанс (удаляет сессионный токен).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Завершает все активные сеансы пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход со всех устройств",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/request-unlock": {
            "post": {
                "description": "Отправляет код разблокировки на email, привязанный к аккаунту.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запросить код разблокировки",
                "parameters": [
                    {
                        "description": "Данные для запроса",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.RequestUnlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/self-block": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Блокирует аккаунт по запросу владельца. Замораживает все счета и завершает все сеансы.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Самоблокировка аккаунта",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/set-pin": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Устанавливает или обновляет PIN-код текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Установить / сменить PIN",
                "parameters": [
                    {
                        "description": "PIN-код",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.SetPinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/unlock": {
            "post": {
                "description": "Проверяет код и разблокирует аккаунт.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Разблокировать аккаунт",
                "parameters": [
                    {
                        "description": "Код разблокировки",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UnlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/currency/exchange": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Конвертирует валюту между банковскими счетами (RUB/USD/EUR).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Обменять валюту между счетами",
                "parameters": [
                    {
                        "description": "Данные обмена",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.ExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/currency/rates": {
            "get": {
                "description": "Возвращает курсы всех валют относительно базовой.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Все курсы валют",
                "parameters": [
                    {
                        "type": "string",
                        "default": "RUB",
                        "description": "Базовая валюта (по умолчанию RUB)",
                        "name": "base",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/currency/rates/{base}/{target}": {
            "get": {
                "description": "Возвращает курс конкретной валютной пары.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Курс валютной пары",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Базовая валюта (RUB, USD, EUR)",
                        "name": "base",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Целевая валюта (RUB, USD, EUR)",
                        "name": "target",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metals/rates": {
            "get": {
                "description": "Возвращает цены на драгоценные металлы (за грамм).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metals"
                ],
                "summary": "Цены на металлы",
                "parameters": [
                    {
                        "type": "string",
                        "default": "RUB",
                        "description": "Базовая валюта (по умолчанию RUB)",
                        "name": "base",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/me": {
            "delete": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Soft delete: статус → deleted, счета заморожены, все сессии отозваны. Данные сохраняются.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-update"
                ],
                "summary": "Удалить аккаунт",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/contacts": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Сохраняет email и номер телефона клиента.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Шаг 4: Контактные данные",
                "parameters": [
                    {
                        "description": "Контактные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.ContactsPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/finalize": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Переносит данные из черновиков в БД, выдаёт сессионный токен и удаляет onboarding-токен.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Завершить регистрацию",
                "responses": {
                    "200": {
                        "description": "status + message + session_token + user_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/identifiers": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Сохраняет идентификаторы налогоплательщика и социального страхования.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Шаг 3: ИНН и СНИЛС",
                "parameters": [
                    {
                        "description": "ИНН и СНИЛС",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.IdentifiersPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/passport": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Сохраняет серию, номер, кем выдан и прочие паспортные сведения.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Шаг 2: Паспортные данные",
                "parameters": [
                    {
                        "description": "Паспортные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.PassportPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/personal-data": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Сохраняет ФИО, дату рождения и пол клиента.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Шаг 1: Персональные данные",
                "parameters": [
                    {
                        "description": "Персональные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.PersonalDataPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/send-email-code": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Отправляет 6-значный код подтверждения на email из шага 4 (contacts).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Отправить код на email",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/account/verify-email": {
            "post": {
                "security": [
                    {
                        "OnboardingToken": []
                    }
                ],
                "description": "Проверяет 6-значный код. После успешной верификации можно вызывать finalize.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Подтвердить email",
                "parameters": [
                    {
                        "description": "Код верификации",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.VerifyEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/contacts": {
            "patch": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Частичное обновление email и/или телефона.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-update"
                ],
                "summary": "Обновить контактные данные",
                "parameters": [
                    {
                        "description": "Контактные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.ContactsUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/passport": {
            "put": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Полная замена паспортных данных (все поля обязательны).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-update"
                ],
                "summary": "Заменить паспортные данные",
                "parameters": [
                    {
                        "description": "Паспортные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.PassportPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/personal-data": {
            "patch": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Частичное обновление ФИО. Дата рождения и пол неизменяемы.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-update"
                ],
                "summary": "Обновить персональные данные",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.PersonalDataUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/start": {
            "post": {
                "description": "Создаёт нового пользователя и возвращает onboarding_token для прохождения шагов регистрации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Начать регистрацию",
                "responses": {
                    "201": {
                        "description": "onboarding_token + status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.AmountPayload": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1000.5
                }
            }
        },
        "schemas.ContactsPayload": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "phone": {
                    "type": "string",
                    "format": "phone",
                    "example": "+79991234567"
                }
            }
        },
        "schemas.ContactsUpdate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "new@example.com"
                },
                "phone": {
                    "type": "string",
                    "format": "phone",
                    "example": "+79990001122"
                }
            }
        },
        "schemas.ExchangeRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 100
                },
                "from_account_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "from-uuid-here"
                },
                "to_account_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "to-uuid-here"
                }
            }
        },
        "schemas.IdentifiersPayload": {
            "type": "object",
            "properties": {
                "inn": {
                    "type": "string",
                    "example": "123456789012"
                },
                "snils": {
                    "type": "string",
                    "example": "12345678900"
                }
            }
        },
        "schemas.LoginPinRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string",
                    "format": "phone",
                    "example": "+79991234567"
                },
                "pin": {
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "schemas.OpenAccountRequest": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "enum": [
                        "RUB",
                        "USD",
                        "EUR"
                    ],
                    "example": "RUB"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "checking",
                        "savings",
                        "credit",
                        "deposit"
                    ],
                    "example": "checking"
                }
            }
        },
        "schemas.PassportPayload": {
            "type": "object",
            "properties": {
                "division_code": {
                    "type": "string",
                    "example": "123-456"
                },
                "expiration_date": {
                    "type": "string",
                    "format": "date",
                    "example": "2030-01-01"
                },
                "issued_at": {
                    "type": "string",
                    "format": "date",
                    "example": "2010-01-01"
                },
                "issued_by": {
                    "type": "string",
                    "example": "ГУ МВД России"
                },
                "number": {
                    "type": "string",
                    "example": "567890"
                },
                "registration_address": {
                    "type": "string",
                    "example": "г. Москва, ул. Пушкина"
                },
                "series": {
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "schemas.PersonalDataPayload": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "format": "date",
                    "example": "1990-01-01"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "M",
                        "F"
                    ],
                    "example": "M"
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Иванович"
                }
            }
        },
        "schemas.PersonalDataUpdate": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "Петр"
                },
                "last_name": {
                    "type": "string",
                    "example": "Петров"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Петрович"
                }
            }
        },
        "schemas.RequestUnlockRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                }
            }
        },
        "schemas.SetPinRequest": {
            "type": "object",
            "properties": {
                "pin": {
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "schemas.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 500
                },
                "description": {
                    "type": "string",
                    "example": "Перевод другу"
                },
                "to_account_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "schemas.UnlockRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                }
            }
        },
        "schemas.VerifyEmailRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "OnboardingToken": {
            "description": "Токен онбординга, полученный из /users/start (TTL 15 минут, скользящая экспирация)",
            "type": "apiKey",
            "name": "X-Onboarding-Token",
            "in": "header"
        },
        "SessionToken": {
            "description": "Сессионный токен, полученный при авторизации",
            "type": "apiKey",
            "name": "X-Session-Token",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Регистрация нового клиента: создание аккаунта, заполнение данных по шагам и финализация. Шаги требуют заголовок X-Onboarding-Token.",
            "name": "onboarding"
        },
        {
            "description": "Обновление данных авторизованного пользователя. Требует заголовок X-Session-Token.",
            "name": "user-update"
        },
        {
            "description": "Аутентификация: вход по PIN-коду, управление сессиями. Защищённые эндпоинты требуют заголовок X-Session-Token.",
            "name": "auth"
        },
        {
            "description": "Банковские счета: открытие, просмотр, закрытие, заморозка.",
            "name": "accounts"
        },
        {
            "description": "Операции по счетам: пополнение, снятие, переводы, история.",
            "name": "transactions"
        },
        {
            "description": "Валютные операции: курсы и обмен между счетами.",
            "name": "currency"
        },
        {
            "description": "Драгоценные металлы: курсы.",
            "name": "metals"
        },
        {
            "description": "Проверка работоспособности сервиса.",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gateway Service API",
	Description:      "API Gateway банковского приложения. Единая точка входа для клиентских запросов: онбординг, аутентификация, управление данными пользователя, счета, транзакции, валюты и металлы.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
