{
 "title": "PostgreSQL Overview",
 "tags": [
  "Postgres",
  "Infrastructure"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Database", "query": { "query": "label_values(pg_up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Connections ($job)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"$job\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Transactions Rate ($job)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{job=\"$job\"}[1m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{job=\"$job\"}[1m]))",
     "legendFormat": "Inserted"
    }
   ]
  },
  {
   "title": "Database Size ($job)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"$job\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}