// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "API Gateway банковского приложения. Единая точка входа для всех клиентских запросов.",
        "title": "Gateway Service API",
        "contact": {},
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/sessions": {
            "post": {
                "description": "Аутентификация по номеру телефона и PIN-коду.",
                "consumes": ["application/json"],
                "tags": ["sessions"],
                "summary": "Вход",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.LoginPinRequest" } }
                ],
                "responses": { "201": { "description": "Created" } }
            },
            "delete": {
                "security": [{"SessionToken": []}],
                "tags": ["sessions"],
                "summary": "Выход (все устройства)",
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/sessions/current": {
            "delete": {
                "security": [{"SessionToken": []}],
                "tags": ["sessions"],
                "summary": "Выход (текущая сессия)",
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/auth/pins": {
            "put": {
                "security": [{"SessionToken": []}],
                "tags": ["auth"],
                "summary": "Сменить PIN-код",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "pin": { "type": "string", "example": "4321" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/auth/unlock-codes": {
            "post": {
                "tags": ["auth"],
                "summary": "Запросить код разблокировки",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "email": { "type": "string", "example": "test@example.com" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/auth/unlock-codes/verifications": {
            "post": {
                "tags": ["auth"],
                "summary": "Подтвердить разблокировку",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "email": { "type": "string", "example": "test@example.com" }, "code": { "type": "string", "example": "123456" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/auth/self-block": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["auth"],
                "summary": "Самоблокировка",
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding": {
            "post": {
                "tags": ["onboarding"],
                "summary": "Начать регистрацию",
                "responses": { "201": { "description": "Created" } }
            }
        },
        "/api/v1/onboarding/personal-data": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Шаг 1: ФИО",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.PersonalDataPayload" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding/passport": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Шаг 2: Паспорт",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.PassportPayload" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding/identifiers": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Шаг 3: ИНН/СНИЛС",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.IdentifiersPayload" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding/contacts": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Шаг 4: Контакты",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.ContactsPayload" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding/email/send": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Отправить код на Email",
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding/email/verify": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Подтвердить Email кодом",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "code": { "type": "string", "example": "123456" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/onboarding/completion": {
            "post": {
                "security": [{"OnboardingToken": []}],
                "tags": ["onboarding"],
                "summary": "Завершить регистрацию",
                "responses": { "200": { "description": "OK", "schema": { "type": "object", "properties": { "status": { "type": "string" }, "message": { "type": "string" }, "session_token": { "type": "string" } } } } }
            }
        },
        "/api/v1/customers/me/personal-data": {
            "patch": {
                "security": [{"SessionToken": []}],
                "tags": ["customers"],
                "summary": "Обновить ФИО",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "last_name": { "type": "string", "example": "НоваяФамилия" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/customers/me/passport": {
            "put": {
                "security": [{"SessionToken": []}],
                "tags": ["customers"],
                "summary": "Сменить паспорт",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.PassportPayload" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/customers/me/contacts": {
            "patch": {
                "security": [{"SessionToken": []}],
                "tags": ["customers"],
                "summary": "Обновить контакты",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.ContactsPayload" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/customers/me": {
            "delete": {
                "security": [{"SessionToken": []}],
                "tags": ["customers"],
                "summary": "Удалить аккаунт",
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/accounts": {
            "get": {
                "security": [{"SessionToken": []}],
                "tags": ["accounts"],
                "summary": "Список счетов",
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["accounts"],
                "summary": "Открыть счет",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.OpenAccountRequest" } }
                ],
                "responses": { "201": { "description": "Created" } }
            }
        },
        "/api/v1/accounts/{account_id}": {
            "get": {
                "security": [{"SessionToken": []}],
                "tags": ["accounts"],
                "summary": "Детали счета",
                "parameters": [{ "name": "account_id", "in": "path", "required": true, "type": "string" }],
                "responses": { "200": { "description": "OK" } }
            },
            "delete": {
                "security": [{"SessionToken": []}],
                "tags": ["accounts"],
                "summary": "Закрыть счет",
                "parameters": [{ "name": "account_id", "in": "path", "required": true, "type": "string" }],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/accounts/{account_id}/suspensions": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["accounts"],
                "summary": "Заморозить счет",
                "parameters": [{ "name": "account_id", "in": "path", "required": true, "type": "string" }],
                "responses": { "200": { "description": "OK" } }
            },
            "delete": {
                "security": [{"SessionToken": []}],
                "tags": ["accounts"],
                "summary": "Разморозить счет",
                "parameters": [{ "name": "account_id", "in": "path", "required": true, "type": "string" }],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/transactions": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["transactions"],
                "summary": "Новая транзакция",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "$ref": "#/definitions/schemas.TransactionCreateRequest" } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/accounts/{account_id}/deposit": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["transactions"],
                "summary": "Пополнение счёта",
                "parameters": [
                    { "name": "account_id", "in": "path", "required": true, "type": "string" },
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "amount": { "type": "number", "example": 1000.0 }, "description": { "type": "string", "example": "Пополнение через кассу" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/accounts/{account_id}/withdraw": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["transactions"],
                "summary": "Снятие со счёта",
                "parameters": [
                    { "name": "account_id", "in": "path", "required": true, "type": "string" },
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "amount": { "type": "number", "example": 500.0 }, "description": { "type": "string", "example": "Снятие в банкомате" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/transfers": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["transactions"],
                "summary": "Перевод средств",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "from_account_id": { "type": "string" }, "to_account_id": { "type": "string" }, "amount": { "type": "number", "example": 200.0 }, "description": { "type": "string", "example": "Перевод другу" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/accounts/{account_id}/transactions": {
            "get": {
                "security": [{"SessionToken": []}],
                "tags": ["transactions"],
                "summary": "История транзакций",
                "parameters": [
                    { "name": "account_id", "in": "path", "required": true, "type": "string" },
                    { "name": "type", "in": "query", "type": "string", "description": "deposit|withdrawal|transfer" }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/currencies/rates": {
            "get": {
                "tags": ["currencies"],
                "summary": "Все курсы валют",
                "parameters": [{ "name": "base", "in": "query", "type": "string", "default": "RUB" }],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/currencies/rates/{base}/{target}": {
            "get": {
                "tags": ["currencies"],
                "summary": "Курс пары",
                "parameters": [
                    { "name": "base", "in": "path", "required": true, "type": "string" },
                    { "name": "target", "in": "path", "required": true, "type": "string" }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/currency-conversions": {
            "post": {
                "security": [{"SessionToken": []}],
                "tags": ["currencies"],
                "summary": "Обмен валюты",
                "parameters": [
                    { "name": "payload", "in": "body", "required": true, "schema": { "type": "object", "properties": { "from_account_id": { "type": "string" }, "to_account_id": { "type": "string" }, "amount": { "type": "number" } } } }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },
        "/api/v1/metals/rates": {
            "get": {
                "tags": ["metals"],
                "summary": "Цены на металлы",
                "parameters": [{ "name": "base", "in": "query", "type": "string", "default": "RUB" }],
                "responses": { "200": { "description": "OK" } }
            }
        }
    },
    "definitions": {
        "schemas.LoginPinRequest": {
            "type": "object",
            "required": ["phone", "pin"],
            "properties": {
                "phone": { "type": "string", "example": "+79001112233" },
                "pin": { "type": "string", "example": "1234" }
            }
        },
        "schemas.OpenAccountRequest": {
            "type": "object",
            "required": ["type", "currency"],
            "properties": {
                "type": { "type": "string", "enum": ["current", "savings"], "example": "current" },
                "currency": { "type": "string", "enum": ["RUB", "USD", "EUR"], "example": "RUB" }
            }
        },
        "schemas.PersonalDataPayload": {
            "type": "object",
            "required": ["last_name", "first_name", "birth_date", "gender"],
            "properties": {
                "last_name": { "type": "string", "example": "Иванов" },
                "first_name": { "type": "string", "example": "Иван" },
                "middle_name": { "type": "string", "example": "Иванович" },
                "birth_date": { "type": "string", "format": "date", "example": "1990-01-01" },
                "gender": { "type": "string", "enum": ["M", "F"], "example": "M" }
            }
        },
        "schemas.PassportPayload": {
            "type": "object",
            "required": ["series", "number", "division_code", "issued_by", "issued_at", "expiration_date", "registration_address"],
            "properties": {
                "series": { "type": "string", "example": "1234" },
                "number": { "type": "string", "example": "567890" },
                "division_code": { "type": "string", "example": "111-222" },
                "issued_by": { "type": "string", "example": "УВД г. Москвы" },
                "issued_at": { "type": "string", "format": "date", "example": "2010-05-15" },
                "expiration_date": { "type": "string", "format": "date", "example": "2030-05-15" },
                "registration_address": { "type": "string", "example": "г. Москва, ул. Ленина, д. 1" }
            }
        },
        "schemas.IdentifiersPayload": {
            "type": "object",
            "required": ["inn", "snils"],
            "properties": {
                "inn": { "type": "string", "example": "123456789012" },
                "snils": { "type": "string", "example": "12345678901" }
            }
        },
        "schemas.ContactsPayload": {
            "type": "object",
            "required": ["email", "phone"],
            "properties": {
                "email": { "type": "string", "example": "ivanov@example.com" },
                "phone": { "type": "string", "example": "+79001112233" }
            }
        },
        "schemas.TransactionCreateRequest": {
            "type": "object",
            "required": ["type", "amount"],
            "properties": {
                "type": { "type": "string", "enum": ["deposit", "withdrawal", "transfer"], "example": "deposit" },
                "amount": { "type": "number", "example": 1000.0 },
                "account_id": { "type": "string", "example": "uuid-ваш-счет" },
                "from_account_id": { "type": "string", "example": "uuid-отправитель" },
                "to_account_id": { "type": "string", "example": "uuid-получатель" },
                "description": { "type": "string", "example": "Пополнение счета" },
                "idempotency_key": { "type": "string", "example": "unique-id-123" }
            }
        }
    },
    "securityDefinitions": {
        "OnboardingToken": { "type": "apiKey", "name": "X-Onboarding-Token", "in": "header" },
        "SessionToken": { "type": "apiKey", "name": "X-Session-Token", "in": "header" }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Gateway Service API",
	Description:      "API Gateway банковского приложения. Полный список всех доступных маршрутов с примерами.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
